### ISSUE TITLE
./install.sh : option not recognized « --rb3 »

### ISSUE THREAD

**Issue by stephane84** [fossfreedom/coverart-browser#380]
Hi,
Installing it on Ubuntu 14.04LTS and Rhythmbox 3.0.2, I get the following error message when installing this plugin : 

     ./install.sh --rb3
     ./install.sh : option non reconnue « --rb3 »
     Usage:
     ./install.sh [OPTION]
     -h, --help      show this message.
     -u, --uninstall uninstall the plugin

It seems this plugin is not working.

Dropping the --rb3 option, the installation succeeded but the plugin is not wokring in Rhymthbox 3 :-(

**Comment by fossfreedom** [comment]
Hi,

  thanks for raising the issue.

Can I ask where you saw that you need to use ./install.sh --rb3 ?  This will need correcting.

Ok - moving on.  Can you describe what you mean "does not work" - what do you see in the plugins window?

Since you are installing manually - you need to also install the plugin coverart-search-providers as well.

Alternatively - all of this is packaged together via my PPA.

The [README](https://github.com/fossfreedom/coverart-browser/blob/release-2.1/README.md) covers all of this - instructions on how to install - the dependencies - as well as the instructions on how to install via PPA.

**Comment by stephane84** [comment]
By using sudo apt-get install rhythmbox-plugin-coverart-browser it worked for me so I'm now enjoying your very nice plugin (ps : is it possible to ask another album art when the picture is not so nice ? Something as... "pick next album art" ... ?)

**Comment by fossfreedom** [comment]
yep - just use your web-browser to find the picture you want - drag and drop the picture onto the album icon.

BTW  - since you've installed via PPA now - please make sure you have deleted the folder ~/.local/share/rhythmbox/plugins/coverart_browser (or similarly named) in the plugins folder.  Your previous manual installation will have installed there.  You need to delete that so that you receive updates via the PPA.
