### ISSUE TITLE
Cannot Load Plugin Rhythmbox 3+ on Fedora 25

### ISSUE THREAD

**Issue by Herodotean** [fossfreedom/coverart-browser#392]
When I click to enable the plugin, I get a "failed to load" error. I have installed and enabled Coverart Browser Search Providers already, and I followed the instructions to the T. All dependencies appear to be installed (tried each one listed, all came back installed already). Not sure what's going wrong.

I'm on Fedora 25 XFCE, and when I started Rhythmbox in the console, this is what it spit back at me:

(rhythmbox:7609): libpeas-WARNING **: Error importing plugin 'coverart_browser':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/[username]/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser.py", line 32, in <module>
    from coverart_browser_source import CoverArtBrowserSource
  File "/home/[username]/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py", line 49, in <module>
    from coverart_artistinfo import ArtistInfoPane
  File "/home/[username]/.local/share/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py", line 28, in <module>
    from gi.repository import WebKit
  File "/usr/lib64/python3.5/site-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit, introspection typelib not found

(rhythmbox:7609): libpeas-WARNING **: Error loading plugin 'coverart_browser'

**Comment by latach** [comment]
This error can be fixed by installing _gir1.2-webkit-3.0_
Please see issue !394

**Comment by Herodotean** [comment]
That seems to be a Debian/Ubuntu fix. This package is not part of Fedora's repositories.

**Comment by dyson** [comment]
For Fedora install `webkitgtk3`.
```
sudo dnf install webkitgtk3
```

**Comment by dyson** [comment]
@Herodotean I saw an email notification mentioning this didn't fix the issue for you but I can't find where you wrote that in GitHub so I'm responding here.

Can you confirm that this didn't resolve your issue?
Do you still get the exact same error? Namely this `ImportError: cannot import name WebKit, introspection typelib not found`?

I had the exact same issue doing a fresh install of the two plugins (coverart-search-providers and coverart-browser) by following the instructions in the README and after installing `webkitgtk3` the issue was resolved.

I am however on Fedora 26 so perhaps that is a difference.

**Comment by Herodotean** [comment]
Hello,


I removed it quickly because I had gotten a different error, "The 'python' plugin loader has not been enabled" when I tried to enable the search providers plugin. I have both Python 2 and Python 3 installed. That's the only error the console spit out at me, too. Oh, and I am on Fedora 26 now.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by dyson** [comment]
Oh right, no worries! I was a little confused there for a minute!

So I can replicate the `The 'python' plugin loader has not been enabled` error if I install the wrong version of the coverart-search-providers (Rhythmbox 2.96 to 2.99.1) which appears first in README.md instead of the version for Rhythmbox 3.0 and later.

I would double check you hadn't done that by accident? Otherwise I'm not sure what else it could be at the moment.

**Comment by IBBoard** [comment]
For reference, on openSUSE the "introspection typelib not found" error means that you're missing `
typelib-1_0-WebKit-1_0`
